services:
  stats-db:
    image: postgres:16.1
    container_name: ewm-stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ewm-stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ewm-stats-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  stats-server:
    build:
      context: .
      dockerfile: ewm-stats-service/ewm-stats-server/Dockerfile
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=secret