CREATE TABLE IF NOT EXISTS users (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
name VARCHAR(250) NOT NULL,
email VARCHAR(254) NOT NULL,
CONSTRAINT pk_users PRIMARY KEY (id),
CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
name VARCHAR(50) NOT NULL,
CONSTRAINT pk_categories PRIMARY KEY (id),
CONSTRAINT uq_categories_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
annotation VARCHAR(2000) NOT NULL,
category_id BIGINT NOT NULL,
created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
description VARCHAR(7000) NOT NULL,
event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
initiator_id BIGINT NOT NULL,
lat DOUBLE PRECISION NOT NULL,
lon DOUBLE PRECISION NOT NULL,
paid BOOLEAN NOT NULL,
participant_limit INTEGER NOT NULL,
published_on TIMESTAMP WITHOUT TIME ZONE,
request_moderation BOOLEAN NOT NULL,
state VARCHAR(32) NOT NULL,
title VARCHAR(120) NOT NULL,
views BIGINT DEFAULT 0,
confirmed_requests BIGINT DEFAULT 0,
CONSTRAINT pk_events PRIMARY KEY (id),
CONSTRAINT fk_events_category FOREIGN KEY (category_id) REFERENCES categories (id),
CONSTRAINT fk_events_initiator FOREIGN KEY (initiator_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS compilations (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
pinned BOOLEAN NOT NULL,
title VARCHAR(50) NOT NULL,
CONSTRAINT pk_compilations PRIMARY KEY (id),
CONSTRAINT uq_compilations_title UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS compilation_events (
compilation_id BIGINT NOT NULL,
event_id BIGINT NOT NULL,
CONSTRAINT pk_compilation_events PRIMARY KEY (compilation_id, event_id),
CONSTRAINT fk_compilation_events_compilation FOREIGN KEY (compilation_id) REFERENCES compilations (id),
CONSTRAINT fk_compilation_events_event FOREIGN KEY (event_id) REFERENCES events (id)
);

CREATE TABLE IF NOT EXISTS requests (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
event_id BIGINT NOT NULL,
requester_id BIGINT NOT NULL,
status VARCHAR(32) NOT NULL,
CONSTRAINT pk_requests PRIMARY KEY (id),
CONSTRAINT fk_requests_event FOREIGN KEY (event_id) REFERENCES events (id),
CONSTRAINT fk_requests_requester FOREIGN KEY (requester_id) REFERENCES users (id),
CONSTRAINT uq_requests_requester_event UNIQUE (requester_id, event_id)
);

CREATE TABLE IF NOT EXISTS comments (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
text VARCHAR(2000) NOT NULL,
author_id BIGINT NOT NULL,
event_id BIGINT NOT NULL,
created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
updated TIMESTAMP WITHOUT TIME ZONE,
state VARCHAR(32) NOT NULL,
rejection_reason VARCHAR(500),
CONSTRAINT pk_comments PRIMARY KEY (id),
CONSTRAINT fk_comments_author FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE,
CONSTRAINT fk_comments_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_events_category ON events (category_id);
CREATE INDEX IF NOT EXISTS idx_events_initiator ON events (initiator_id);
CREATE INDEX IF NOT EXISTS idx_events_event_date ON events (event_date);
CREATE INDEX IF NOT EXISTS idx_events_state ON events (state);

CREATE INDEX IF NOT EXISTS idx_requests_event ON requests (event_id);
CREATE INDEX IF NOT EXISTS idx_requests_requester ON requests (requester_id);
CREATE INDEX IF NOT EXISTS idx_requests_status ON requests (status);

CREATE INDEX IF NOT EXISTS idx_compilations_pinned ON compilations (pinned);

CREATE INDEX IF NOT EXISTS idx_comments_event_id ON comments (event_id);
CREATE INDEX IF NOT EXISTS idx_comments_author_id ON comments (author_id);
CREATE INDEX IF NOT EXISTS idx_comments_state ON comments (state);
CREATE INDEX IF NOT EXISTS idx_comments_created ON comments (created);