    CREATE TABLE IF NOT EXISTS hits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app VARCHAR(255) NOT NULL,
    uri VARCHAR(2048) NOT NULL,
    ip VARCHAR(64) NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_hits PRIMARY KEY (id)
    );

    CREATE INDEX IF NOT EXISTS idx_hits_created ON hits (created);
    CREATE INDEX IF NOT EXISTS idx_hits_uri ON hits (uri);
    CREATE INDEX IF NOT EXISTS idx_hits_app ON hits (app);
    CREATE INDEX IF NOT EXISTS idx_hits_ip ON hits (ip);